MAPS_PATH = '/home/svcapp/userdata/musicai/MAPS'
# MAESTRO_PATH = '/home/svcapp/userdata/maestro-v2.0.0'
# LOG_DIR_PRE = '/home/svcapp/userdata/amt_model/'
MAESTRO_PATH = '/output/maestro-v2.0.0'
LOG_DIR_PRE = '/output/amt_model/'